name: mopac
channels:
  - conda-canary
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - brotlipy=0.7.0=py36h7b6447c_1000
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py36h9f0ad1d_0
  - cffi=1.11.5=py36_0
  - chardet=3.0.4=py36_1003
  - conda=4.8.4=py36_0
  - conda-package-handling=1.6.1=py36h7b6447c_0
  - hdf5=1.10.6=nompi_h3c11f04_101
  - importlib-metadata=1.7.0=py36h9f0ad1d_0
  - krb5=1.17.1=hfafb76e_3
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcurl=7.71.1=hcdd3856_5
  - libedit=3.1.20191231=h14c3975_1
  - libev=4.33=h516909a_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=hdf63c60_16
  - liblapack=3.8.0=17_openblas
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=hed695b0_2
  - libprotobuf=3.13.0=h8b12597_0
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mock=4.0.2=py36h9f0ad1d_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1g=h516909a_1
  - patchelf=0.9=he6710b0_3
  - pip=20.2.2=py36_0
  - pycosat=0.6.3=py36h7b6447c_0
  - python=3.6.10=h7579374_2
  - python_abi=3.6=1_cp36m
  - readline=8.0=h7b6447c_0
  - ruamel_yaml=0.15.87=py36h7b6447c_1
  - setuptools=49.6.0=py36_0
  - sqlite=3.33.0=h62c20be_0
  - tensorboard=1.13.1=py36_0
  - tensorflow=1.13.1=py36h90a7d86_1
  - tensorflow-base=1.13.1=py36h76b4ce7_8
  - tensorflow-estimator=1.13.0=py_0
  - tensorflow-gpu=1.13.1=h0d30ee6_0
  - termcolor=1.1.0=py_2
  - tk=8.6.10=hbc83047_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.6.1
    - asn1crypto==0.24.0
    - astor==0.7.1
    - atomicwrites==1.2.1
    - attrs==18.2.0
    - boto3==1.9.57
    - botocore==1.12.57
    - cachetools==3.0.0
    - click==7.0
    - cloudpickle==0.6.1
    - colorama==0.3.9
    - cryptography==2.3.1
    - cycler==0.10.0
    - cython==0.29.21
    - dask==1.0.0
    - decorator==4.3.0
    - deepdiff==3.3.0
    - docutils==0.14
    - dotmap==1.3.8
    - fasteners==0.15
    - filelock==3.0.12
    - flask==1.0.2
    - flatbuffers==1.10
    - funcsigs==1.0.2
    - future==0.17.1
    - gast==0.2.0
    - gitdb2==2.0.5
    - gitpython==2.1.11
    - glfw==1.7.0
    - google-api-python-client==1.7.5
    - google-auth==1.6.1
    - google-auth-httplib2==0.0.3
    - gpflow==1.4.1
    - grpcio==1.16.1
    - gtimer==1.0.0b5
    - gym==0.12.0
    - h5py==2.8.0
    - httplib2==0.12.0
    - idna==2.7
    - imageio==2.4.1
    - ipython-genutils==0.2.0
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - jmespath==0.9.3
    - jsonpickle==1.4.1
    - jsonschema==3.2.0
    - jupyter-core==4.6.3
    - keras-applications==1.0.6
    - keras-preprocessing==1.0.5
    - kiwisolver==1.0.1
    - lockfile==0.12.2
    - lz4==3.1.0
    - markdown==3.0.1
    - markupsafe==1.1.1
    - matplotlib==2.0.2
    - monotonic==1.5
    - more-itertools==4.3.0
    - mujoco-py==2.0.2.10
    - multipledispatch==0.6.0
    - git+https://github.com/vitchyr/multiworld.git@d76b3dae2e8cbca02924f93d6cc0239c552f6408
    - nbformat==5.0.7
    - networkx==2.2
    - numpy==1.16.0
    - opencv-python-headless==4.4.0.42
    - pandas==0.23.4
    - pillow==6.2.0
    - plotly==3.4.2
    - pluggy==0.8.0
    - protobuf==3.6.1
    - psutil==5.7.2
    - py==1.7.0
    - py-spy==0.3.3
    - pyasn1==0.4.4
    - pyasn1-modules==0.2.2
    - pycparser==2.19
    - pygame==1.9.4
    - pyglet==1.3.2
    - pyopenssl==18.0.0
    - pyparsing==2.3.0
    - pyrsistent==0.16.0
    - pysocks==1.6.8
    - pytest==4.0.1
    - python-dateutil==2.7.5
    - pytz==2018.7
    - pywavelets==1.0.1
    - pyyaml==4.2b4
    - ray==0.6.4
    - redis==3.0.1
    - requests==2.20.1
    - retrying==1.3.3
    - rsa==3.4.2
    - s3transfer==0.1.13
    - scikit-image==0.14.2
    - scikit-learn==0.20.1
    - scipy==1.1.0
    - git+https://github.com/hartikainen/serializable.git@76516385a3a716ed4a2a9ad877e2d5cbcf18d4e6
    - setproctitle==1.1.10
    - six==1.11.0
    - smmap2==2.0.5
    - tensorboardx==1.8
    - tensorflow-probability==0.6.0
    - toolz==0.9.0
    - torch==1.6.0
    - tqdm==4.32.1
    - traitlets==4.3.3
    - typing==3.7.4.3
    - uritemplate==3.0.0
    - urllib3==1.24.2
    - werkzeug==0.15.3
